# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_TimeSeriesView.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget_TimeSeriesView(object):
    def setupUi(self, Widget_TimeSeriesView):
        Widget_TimeSeriesView.setObjectName("Widget_TimeSeriesView")
        Widget_TimeSeriesView.resize(857, 663)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget_TimeSeriesView)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_LeftPane = QtWidgets.QGridLayout()
        self.gridLayout_LeftPane.setObjectName("gridLayout_LeftPane")
        self.checkBoxShowArrow = QtWidgets.QCheckBox(Widget_TimeSeriesView)
        self.checkBoxShowArrow.setObjectName("checkBoxShowArrow")
        self.gridLayout_LeftPane.addWidget(self.checkBoxShowArrow, 16, 1, 1, 1)
        self.btnSetColor3D = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnSetColor3D.setObjectName("btnSetColor3D")
        self.gridLayout_LeftPane.addWidget(self.btnSetColor3D, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_10.setObjectName("label_10")
        self.gridLayout_LeftPane.addWidget(self.label_10, 13, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_9.setObjectName("label_9")
        self.gridLayout_LeftPane.addWidget(self.label_9, 3, 2, 1, 1)
        self.btnStreamline = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnStreamline.setObjectName("btnStreamline")
        self.gridLayout_LeftPane.addWidget(self.btnStreamline, 11, 1, 1, 1)
        self.btnCalculate = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnCalculate.setObjectName("btnCalculate")
        self.gridLayout_LeftPane.addWidget(self.btnCalculate, 10, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_3.setObjectName("label_3")
        self.gridLayout_LeftPane.addWidget(self.label_3, 10, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_6.setObjectName("label_6")
        self.gridLayout_LeftPane.addWidget(self.label_6, 2, 0, 1, 1)
        self.btnCut = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnCut.setObjectName("btnCut")
        self.gridLayout_LeftPane.addWidget(self.btnCut, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_4.setObjectName("label_4")
        self.gridLayout_LeftPane.addWidget(self.label_4, 6, 0, 1, 1)
        self.btnLoadBackground = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnLoadBackground.setObjectName("btnLoadBackground")
        self.gridLayout_LeftPane.addWidget(self.btnLoadBackground, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_5.setObjectName("label_5")
        self.gridLayout_LeftPane.addWidget(self.label_5, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label.setObjectName("label")
        self.gridLayout_LeftPane.addWidget(self.label, 4, 0, 1, 1)
        self.sliderColorWindow = QtWidgets.QSlider(Widget_TimeSeriesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderColorWindow.sizePolicy().hasHeightForWidth())
        self.sliderColorWindow.setSizePolicy(sizePolicy)
        self.sliderColorWindow.setMinimumSize(QtCore.QSize(100, 0))
        self.sliderColorWindow.setOrientation(QtCore.Qt.Horizontal)
        self.sliderColorWindow.setObjectName("sliderColorWindow")
        self.gridLayout_LeftPane.addWidget(self.sliderColorWindow, 3, 1, 1, 1)
        self.btnPathline = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnPathline.setObjectName("btnPathline")
        self.gridLayout_LeftPane.addWidget(self.btnPathline, 12, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_LeftPane.addItem(spacerItem, 18, 0, 1, 1)
        self.sliderColorLevel = QtWidgets.QSlider(Widget_TimeSeriesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderColorLevel.sizePolicy().hasHeightForWidth())
        self.sliderColorLevel.setSizePolicy(sizePolicy)
        self.sliderColorLevel.setMinimumSize(QtCore.QSize(100, 0))
        self.sliderColorLevel.setOrientation(QtCore.Qt.Horizontal)
        self.sliderColorLevel.setObjectName("sliderColorLevel")
        self.gridLayout_LeftPane.addWidget(self.sliderColorLevel, 2, 1, 1, 1)
        self.checkBoxShowRayCast = QtWidgets.QCheckBox(Widget_TimeSeriesView)
        self.checkBoxShowRayCast.setObjectName("checkBoxShowRayCast")
        self.gridLayout_LeftPane.addWidget(self.checkBoxShowRayCast, 14, 1, 1, 1)
        self.btnCutReset = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnCutReset.setObjectName("btnCutReset")
        self.gridLayout_LeftPane.addWidget(self.btnCutReset, 8, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_8.setObjectName("label_8")
        self.gridLayout_LeftPane.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_2.setObjectName("label_2")
        self.gridLayout_LeftPane.addWidget(self.label_2, 0, 0, 1, 1)
        self.sliderTimePhase = QtWidgets.QSlider(Widget_TimeSeriesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderTimePhase.sizePolicy().hasHeightForWidth())
        self.sliderTimePhase.setSizePolicy(sizePolicy)
        self.sliderTimePhase.setMinimumSize(QtCore.QSize(100, 0))
        self.sliderTimePhase.setPageStep(1)
        self.sliderTimePhase.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTimePhase.setObjectName("sliderTimePhase")
        self.gridLayout_LeftPane.addWidget(self.sliderTimePhase, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_11.setObjectName("label_11")
        self.gridLayout_LeftPane.addWidget(self.label_11, 15, 0, 1, 1)
        self.checkBoxShowHedgehog = QtWidgets.QCheckBox(Widget_TimeSeriesView)
        self.checkBoxShowHedgehog.setObjectName("checkBoxShowHedgehog")
        self.gridLayout_LeftPane.addWidget(self.checkBoxShowHedgehog, 15, 1, 1, 1)
        self.labelTimePhase = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.labelTimePhase.setObjectName("labelTimePhase")
        self.gridLayout_LeftPane.addWidget(self.labelTimePhase, 0, 2, 1, 1)
        self.checkBoxShowSurface = QtWidgets.QCheckBox(Widget_TimeSeriesView)
        self.checkBoxShowSurface.setObjectName("checkBoxShowSurface")
        self.gridLayout_LeftPane.addWidget(self.checkBoxShowSurface, 13, 1, 1, 1)
        self.btnPlaneWidget = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnPlaneWidget.setObjectName("btnPlaneWidget")
        self.gridLayout_LeftPane.addWidget(self.btnPlaneWidget, 6, 1, 1, 1)
        self.btnExportSegmentation = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnExportSegmentation.setObjectName("btnExportSegmentation")
        self.gridLayout_LeftPane.addWidget(self.btnExportSegmentation, 9, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_7.setObjectName("label_7")
        self.gridLayout_LeftPane.addWidget(self.label_7, 3, 0, 1, 1)
        self.btnAnimationStartStop = QtWidgets.QPushButton(Widget_TimeSeriesView)
        self.btnAnimationStartStop.setObjectName("btnAnimationStartStop")
        self.gridLayout_LeftPane.addWidget(self.btnAnimationStartStop, 17, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.label_12.setObjectName("label_12")
        self.gridLayout_LeftPane.addWidget(self.label_12, 17, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_LeftPane)
        self.gridLayout_RightPane = QtWidgets.QGridLayout()
        self.gridLayout_RightPane.setObjectName("gridLayout_RightPane")
        self.verticalLayoutPane4 = QtWidgets.QVBoxLayout()
        self.verticalLayoutPane4.setSpacing(0)
        self.verticalLayoutPane4.setObjectName("verticalLayoutPane4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitlePane4 = QtWidgets.QLabel(Widget_TimeSeriesView)
        self.labelTitlePane4.setObjectName("labelTitlePane4")
        self.verticalLayout.addWidget(self.labelTitlePane4)
        self.checkShowLargest = QtWidgets.QCheckBox(Widget_TimeSeriesView)
        self.checkShowLargest.setChecked(True)
        self.checkShowLargest.setObjectName("checkShowLargest")
        self.verticalLayout.addWidget(self.checkShowLargest)
        self.verticalLayoutPane4.addLayout(self.verticalLayout)
        self.vtkWidgetVolumeRender = QVTKRenderWindowInteractor(Widget_TimeSeriesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkWidgetVolumeRender.sizePolicy().hasHeightForWidth())
        self.vtkWidgetVolumeRender.setSizePolicy(sizePolicy)
        self.vtkWidgetVolumeRender.setMinimumSize(QtCore.QSize(100, 100))
        self.vtkWidgetVolumeRender.setObjectName("vtkWidgetVolumeRender")
        self.verticalLayoutPane4.addWidget(self.vtkWidgetVolumeRender)
        self.sliderPane4 = QtWidgets.QSlider(Widget_TimeSeriesView)
        self.sliderPane4.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPane4.setObjectName("sliderPane4")
        self.verticalLayoutPane4.addWidget(self.sliderPane4)
        self.gridLayout_RightPane.addLayout(self.verticalLayoutPane4, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_RightPane)

        self.retranslateUi(Widget_TimeSeriesView)
        QtCore.QMetaObject.connectSlotsByName(Widget_TimeSeriesView)

    def retranslateUi(self, Widget_TimeSeriesView):
        _translate = QtCore.QCoreApplication.translate
        Widget_TimeSeriesView.setWindowTitle(_translate("Widget_TimeSeriesView", "Time Series View"))
        self.checkBoxShowArrow.setText(_translate("Widget_TimeSeriesView", "Arrow"))
        self.btnSetColor3D.setText(_translate("Widget_TimeSeriesView", "3D Color"))
        self.label_10.setText(_translate("Widget_TimeSeriesView", "Scalar"))
        self.label_9.setText(_translate("Widget_TimeSeriesView", "0 / 1000 / 1000"))
        self.btnStreamline.setText(_translate("Widget_TimeSeriesView", "Streamline"))
        self.btnCalculate.setText(_translate("Widget_TimeSeriesView", "Calculate"))
        self.label_3.setText(_translate("Widget_TimeSeriesView", "Result"))
        self.label_6.setText(_translate("Widget_TimeSeriesView", "Color Level"))
        self.btnCut.setText(_translate("Widget_TimeSeriesView", "Cut"))
        self.label_4.setText(_translate("Widget_TimeSeriesView", "Segmentation"))
        self.btnLoadBackground.setText(_translate("Widget_TimeSeriesView", "Load Background"))
        self.label_5.setText(_translate("Widget_TimeSeriesView", "Window control"))
        self.label.setText(_translate("Widget_TimeSeriesView", "Visualization"))
        self.btnPathline.setText(_translate("Widget_TimeSeriesView", "Pathline"))
        self.checkBoxShowRayCast.setText(_translate("Widget_TimeSeriesView", "Ray Cast"))
        self.btnCutReset.setText(_translate("Widget_TimeSeriesView", "Reset Cut"))
        self.label_8.setText(_translate("Widget_TimeSeriesView", "0 / 500 / 1000"))
        self.label_2.setText(_translate("Widget_TimeSeriesView", "Time Phase"))
        self.label_11.setText(_translate("Widget_TimeSeriesView", "Vector"))
        self.checkBoxShowHedgehog.setText(_translate("Widget_TimeSeriesView", "Hedgehog"))
        self.labelTimePhase.setText(_translate("Widget_TimeSeriesView", "1 / 16"))
        self.checkBoxShowSurface.setText(_translate("Widget_TimeSeriesView", "Surface"))
        self.btnPlaneWidget.setText(_translate("Widget_TimeSeriesView", "Plane Widget"))
        self.btnExportSegmentation.setText(_translate("Widget_TimeSeriesView", "Export"))
        self.label_7.setText(_translate("Widget_TimeSeriesView", "Color Window"))
        self.btnAnimationStartStop.setText(_translate("Widget_TimeSeriesView", "Start"))
        self.label_12.setText(_translate("Widget_TimeSeriesView", "Animation"))
        self.labelTitlePane4.setText(_translate("Widget_TimeSeriesView", "Volume Render"))
        self.checkShowLargest.setText(_translate("Widget_TimeSeriesView", "Show Largest Region Only"))

from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget_TimeSeriesView = QtWidgets.QWidget()
    ui = Ui_Widget_TimeSeriesView()
    ui.setupUi(Widget_TimeSeriesView)
    Widget_TimeSeriesView.show()
    sys.exit(app.exec_())

