# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_2DSliceView.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget_2DSliceView(object):
    def setupUi(self, Widget_2DSliceView):
        Widget_2DSliceView.setObjectName("Widget_2DSliceView")
        Widget_2DSliceView.resize(857, 663)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget_2DSliceView)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_LeftPane = QtWidgets.QGridLayout()
        self.gridLayout_LeftPane.setObjectName("gridLayout_LeftPane")
        self.label = QtWidgets.QLabel(Widget_2DSliceView)
        self.label.setObjectName("label")
        self.gridLayout_LeftPane.addWidget(self.label, 4, 0, 1, 1)
        self.sliderColorWindow = QtWidgets.QSlider(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderColorWindow.sizePolicy().hasHeightForWidth())
        self.sliderColorWindow.setSizePolicy(sizePolicy)
        self.sliderColorWindow.setMinimumSize(QtCore.QSize(100, 0))
        self.sliderColorWindow.setOrientation(QtCore.Qt.Horizontal)
        self.sliderColorWindow.setObjectName("sliderColorWindow")
        self.gridLayout_LeftPane.addWidget(self.sliderColorWindow, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Widget_2DSliceView)
        self.label_2.setObjectName("label_2")
        self.gridLayout_LeftPane.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnPlaneWidget = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnPlaneWidget.setObjectName("btnPlaneWidget")
        self.gridLayout_LeftPane.addWidget(self.btnPlaneWidget, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Widget_2DSliceView)
        self.label_4.setObjectName("label_4")
        self.gridLayout_LeftPane.addWidget(self.label_4, 6, 0, 1, 1)
        self.btnCalculate = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnCalculate.setObjectName("btnCalculate")
        self.gridLayout_LeftPane.addWidget(self.btnCalculate, 10, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_LeftPane.addItem(spacerItem, 13, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Widget_2DSliceView)
        self.label_5.setObjectName("label_5")
        self.gridLayout_LeftPane.addWidget(self.label_5, 1, 0, 1, 1)
        self.btnCutReset = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnCutReset.setObjectName("btnCutReset")
        self.gridLayout_LeftPane.addWidget(self.btnCutReset, 8, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Widget_2DSliceView)
        self.label_7.setObjectName("label_7")
        self.gridLayout_LeftPane.addWidget(self.label_7, 3, 0, 1, 1)
        self.btnLoadBackground = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnLoadBackground.setObjectName("btnLoadBackground")
        self.gridLayout_LeftPane.addWidget(self.btnLoadBackground, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Widget_2DSliceView)
        self.label_3.setObjectName("label_3")
        self.gridLayout_LeftPane.addWidget(self.label_3, 10, 0, 1, 1)
        self.sliderTimePhase = QtWidgets.QSlider(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderTimePhase.sizePolicy().hasHeightForWidth())
        self.sliderTimePhase.setSizePolicy(sizePolicy)
        self.sliderTimePhase.setMinimumSize(QtCore.QSize(100, 0))
        self.sliderTimePhase.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTimePhase.setObjectName("sliderTimePhase")
        self.gridLayout_LeftPane.addWidget(self.sliderTimePhase, 0, 1, 1, 1)
        self.btnSetColor3D = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnSetColor3D.setObjectName("btnSetColor3D")
        self.gridLayout_LeftPane.addWidget(self.btnSetColor3D, 4, 1, 1, 1)
        self.btnExportSegmentation = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnExportSegmentation.setObjectName("btnExportSegmentation")
        self.gridLayout_LeftPane.addWidget(self.btnExportSegmentation, 9, 1, 1, 1)
        self.btnCut = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnCut.setObjectName("btnCut")
        self.gridLayout_LeftPane.addWidget(self.btnCut, 7, 1, 1, 1)
        self.sliderColorLevel = QtWidgets.QSlider(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderColorLevel.sizePolicy().hasHeightForWidth())
        self.sliderColorLevel.setSizePolicy(sizePolicy)
        self.sliderColorLevel.setMinimumSize(QtCore.QSize(100, 0))
        self.sliderColorLevel.setOrientation(QtCore.Qt.Horizontal)
        self.sliderColorLevel.setObjectName("sliderColorLevel")
        self.gridLayout_LeftPane.addWidget(self.sliderColorLevel, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Widget_2DSliceView)
        self.label_6.setObjectName("label_6")
        self.gridLayout_LeftPane.addWidget(self.label_6, 2, 0, 1, 1)
        self.btnStreamline = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnStreamline.setObjectName("btnStreamline")
        self.gridLayout_LeftPane.addWidget(self.btnStreamline, 11, 1, 1, 1)
        self.btnPathline = QtWidgets.QPushButton(Widget_2DSliceView)
        self.btnPathline.setObjectName("btnPathline")
        self.gridLayout_LeftPane.addWidget(self.btnPathline, 12, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_LeftPane)
        self.gridLayout_RightPane = QtWidgets.QGridLayout()
        self.gridLayout_RightPane.setObjectName("gridLayout_RightPane")
        self.verticalLayoutPane1 = QtWidgets.QVBoxLayout()
        self.verticalLayoutPane1.setObjectName("verticalLayoutPane1")
        self.labelTitlePane1 = QtWidgets.QLabel(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitlePane1.sizePolicy().hasHeightForWidth())
        self.labelTitlePane1.setSizePolicy(sizePolicy)
        self.labelTitlePane1.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTitlePane1.setObjectName("labelTitlePane1")
        self.verticalLayoutPane1.addWidget(self.labelTitlePane1)
        self.vtkWidgetPane1 = QVTKRenderWindowInteractor(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkWidgetPane1.sizePolicy().hasHeightForWidth())
        self.vtkWidgetPane1.setSizePolicy(sizePolicy)
        self.vtkWidgetPane1.setMinimumSize(QtCore.QSize(100, 100))
        self.vtkWidgetPane1.setObjectName("vtkWidgetPane1")
        self.verticalLayoutPane1.addWidget(self.vtkWidgetPane1)
        self.sliderPane1 = QtWidgets.QSlider(Widget_2DSliceView)
        self.sliderPane1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPane1.setObjectName("sliderPane1")
        self.verticalLayoutPane1.addWidget(self.sliderPane1)
        self.gridLayout_RightPane.addLayout(self.verticalLayoutPane1, 0, 0, 1, 1)
        self.verticalLayoutPane2 = QtWidgets.QVBoxLayout()
        self.verticalLayoutPane2.setObjectName("verticalLayoutPane2")
        self.labelTitlePane2 = QtWidgets.QLabel(Widget_2DSliceView)
        self.labelTitlePane2.setObjectName("labelTitlePane2")
        self.verticalLayoutPane2.addWidget(self.labelTitlePane2)
        self.vtkWidgetPane2 = QVTKRenderWindowInteractor(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkWidgetPane2.sizePolicy().hasHeightForWidth())
        self.vtkWidgetPane2.setSizePolicy(sizePolicy)
        self.vtkWidgetPane2.setMinimumSize(QtCore.QSize(100, 100))
        self.vtkWidgetPane2.setObjectName("vtkWidgetPane2")
        self.verticalLayoutPane2.addWidget(self.vtkWidgetPane2)
        self.sliderPane2 = QtWidgets.QSlider(Widget_2DSliceView)
        self.sliderPane2.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPane2.setObjectName("sliderPane2")
        self.verticalLayoutPane2.addWidget(self.sliderPane2)
        self.gridLayout_RightPane.addLayout(self.verticalLayoutPane2, 0, 2, 1, 1)
        self.verticalLayoutPane4 = QtWidgets.QVBoxLayout()
        self.verticalLayoutPane4.setSpacing(0)
        self.verticalLayoutPane4.setObjectName("verticalLayoutPane4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitlePane4 = QtWidgets.QLabel(Widget_2DSliceView)
        self.labelTitlePane4.setObjectName("labelTitlePane4")
        self.verticalLayout.addWidget(self.labelTitlePane4)
        self.checkShowLargest = QtWidgets.QCheckBox(Widget_2DSliceView)
        self.checkShowLargest.setChecked(True)
        self.checkShowLargest.setObjectName("checkShowLargest")
        self.verticalLayout.addWidget(self.checkShowLargest)
        self.verticalLayoutPane4.addLayout(self.verticalLayout)
        self.vtkWidgetPane4 = QVTKRenderWindowInteractor(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkWidgetPane4.sizePolicy().hasHeightForWidth())
        self.vtkWidgetPane4.setSizePolicy(sizePolicy)
        self.vtkWidgetPane4.setMinimumSize(QtCore.QSize(100, 100))
        self.vtkWidgetPane4.setObjectName("vtkWidgetPane4")
        self.verticalLayoutPane4.addWidget(self.vtkWidgetPane4)
        self.sliderPane4 = QtWidgets.QSlider(Widget_2DSliceView)
        self.sliderPane4.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPane4.setObjectName("sliderPane4")
        self.verticalLayoutPane4.addWidget(self.sliderPane4)
        self.gridLayout_RightPane.addLayout(self.verticalLayoutPane4, 2, 2, 1, 1)
        self.verticalLayoutPane3 = QtWidgets.QVBoxLayout()
        self.verticalLayoutPane3.setObjectName("verticalLayoutPane3")
        self.labelTitlePane3 = QtWidgets.QLabel(Widget_2DSliceView)
        self.labelTitlePane3.setObjectName("labelTitlePane3")
        self.verticalLayoutPane3.addWidget(self.labelTitlePane3)
        self.vtkWidgetPane3 = QVTKRenderWindowInteractor(Widget_2DSliceView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkWidgetPane3.sizePolicy().hasHeightForWidth())
        self.vtkWidgetPane3.setSizePolicy(sizePolicy)
        self.vtkWidgetPane3.setMinimumSize(QtCore.QSize(100, 100))
        self.vtkWidgetPane3.setObjectName("vtkWidgetPane3")
        self.verticalLayoutPane3.addWidget(self.vtkWidgetPane3)
        self.sliderPane3 = QtWidgets.QSlider(Widget_2DSliceView)
        self.sliderPane3.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPane3.setObjectName("sliderPane3")
        self.verticalLayoutPane3.addWidget(self.sliderPane3)
        self.gridLayout_RightPane.addLayout(self.verticalLayoutPane3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_RightPane)

        self.retranslateUi(Widget_2DSliceView)
        QtCore.QMetaObject.connectSlotsByName(Widget_2DSliceView)

    def retranslateUi(self, Widget_2DSliceView):
        _translate = QtCore.QCoreApplication.translate
        Widget_2DSliceView.setWindowTitle(_translate("Widget_2DSliceView", "2D Slice View"))
        self.label.setText(_translate("Widget_2DSliceView", "Visualization"))
        self.label_2.setText(_translate("Widget_2DSliceView", "Time Phase"))
        self.btnPlaneWidget.setText(_translate("Widget_2DSliceView", "Plane Widget"))
        self.label_4.setText(_translate("Widget_2DSliceView", "Segmentation"))
        self.btnCalculate.setText(_translate("Widget_2DSliceView", "Calculate"))
        self.label_5.setText(_translate("Widget_2DSliceView", "Window control"))
        self.btnCutReset.setText(_translate("Widget_2DSliceView", "Reset Cut"))
        self.label_7.setText(_translate("Widget_2DSliceView", "Color Window"))
        self.btnLoadBackground.setText(_translate("Widget_2DSliceView", "Load Background"))
        self.label_3.setText(_translate("Widget_2DSliceView", "Result"))
        self.btnSetColor3D.setText(_translate("Widget_2DSliceView", "3D Color"))
        self.btnExportSegmentation.setText(_translate("Widget_2DSliceView", "Export"))
        self.btnCut.setText(_translate("Widget_2DSliceView", "Cut"))
        self.label_6.setText(_translate("Widget_2DSliceView", "Color Level"))
        self.btnStreamline.setText(_translate("Widget_2DSliceView", "Streamline"))
        self.btnPathline.setText(_translate("Widget_2DSliceView", "Pathline"))
        self.labelTitlePane1.setText(_translate("Widget_2DSliceView", "XY slice"))
        self.labelTitlePane2.setText(_translate("Widget_2DSliceView", "YZ slice"))
        self.labelTitlePane4.setText(_translate("Widget_2DSliceView", "Volume Render"))
        self.checkShowLargest.setText(_translate("Widget_2DSliceView", "Show Largest Region Only"))
        self.labelTitlePane3.setText(_translate("Widget_2DSliceView", "XZ slice"))

from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget_2DSliceView = QtWidgets.QWidget()
    ui = Ui_Widget_2DSliceView()
    ui.setupUi(Widget_2DSliceView)
    Widget_2DSliceView.show()
    sys.exit(app.exec_())

